language: java
sudo: false

jdk:
  - oraclejdk11
  
cache:
  directories:
  - $HOME/.m2

jobs:

  include:
    - stage: "Build modules & pre-cache"
      script: false

    - stage: "Unit Tests"

      name : "Common"
      install: mvn install -pl common -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -pl common -Dtest=\!CucumberRunnerTest test
    - #Same stage
      install: mvn install -pl client -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -pl client -Dtest=\!CucumberRunnerTest test
      name : "Client"
    - #Same stage
      install: mvn install -pl server -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -pl server -Dtest=\!CucumberRunnerTest test
      name : "Server"

    - stage: "Integration Tests"
      install: mvn install -pl common -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      name : "Common"
      script: mvn -pl common -Dtest=CucumberRunnerTest test
    - #Same stage
      install: mvn install -pl client -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -pl client -Dtest=CucumberRunnerTest test
      name : "Client"
    - #Same stage
      install: mvn install -pl server -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -pl server -Dtest=CucumberRunnerTest test
      name : "Server"

    - stage : "Deploy to DockerHub"
      language: generic
      install: false
      name: "Server"
      script :
        - docker build -t topinambours/takenoko:latest-server . -f ./dp/DockerfileServer
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push topinambours/takenoko:latest-server
    - # Same stage
      language: generic
      install: false
      script:
        - docker build -t topinambours/takenoko:latest-client . -f ./dp/DockerfileClient
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push topinambours/takenoko:latest-client
      name: "Client"
    - # Same stage
      language: generic
      install: false
      script:
        - sudo docker build -t topinambours/takenoko:latest-testSuite ./dp -f ./dp/DockerfileTestSuite
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push topinambours/takenoko:latest-testSuite
      name: "Test suite"

    - stage: "Deploy Tests (2 vcores)"
      language: generic
      install: false
      name: "5 sequential games run"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull topinambours/takenoko:latest-testSuite
        - docker run -it --network host -v /var/run/docker.sock:/var/run/docker.sock topinambours/takenoko:latest-testSuite -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" --mode sequential -g2 3 -g3 1 -g4 1
    - # Same stage
      language: generic
      install: false
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull topinambours/takenoko:latest-testSuite
        - docker run -it --network host -v /var/run/docker.sock:/var/run/docker.sock topinambours/takenoko:latest-testSuite -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" --mode sequential -g2 20 -g3 15 -g4 15
      name: "50 sequential games run"
    - # Same stage
      language: generic
      install: false
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull topinambours/takenoko:latest-testSuite
        - docker run -it --network host -v /var/run/docker.sock:/var/run/docker.sock topinambours/takenoko:latest-testSuite -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" --mode parallel -g2 1 -g3 1 -g4 1
      name: "3 parallel games run (9 clients)"
    - # Same stage
      language: generic
      install: false
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull topinambours/takenoko:latest-testSuite
        - docker run -it --network host -v /var/run/docker.sock:/var/run/docker.sock topinambours/takenoko:latest-testSuite -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" --mode parallel -g2 2 -g3 2 -g4 2
      name: "10 parallel games run (18 clients)"






