language: java
sudo: false

env:
  global:
  - CODECOV_TOKEN=:uuid-repo-token

jdk:
  - openjdk10
script:
  - mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9cd957f7-8fa1-40cc-9e96-70f4114b5969

