language: java
sudo: false

jdk:
  - openjdk10

jobs:
  include:
    - stage: test
      script:
        - mvn test
    - stage : deploy
      script :
        - mvn package
        - docker build -t topinambours/takenoko .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push topinambours/takenoko:latest
